# Basic
name:               "LIBRE_hub"
title:              "The Latin American Hub for Bioimaging Through Open Hardware (LIBRE_hub)"
description:        "A training network for open source bioimaging hardware in Latin America with the goal to empower regional researchers through practical workshops, seminars, networking, and online resources adapted to local needs and re-published in local languages."


# URL
url:                #TBD
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
 # - name:           "publications"
  #  href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "seminars"
    href:           "/seminars"
  - name:           "resources"
    href:           "/docu"
  - name:           "join"
    href:           "/join"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
